import About from "@/components/About/About";
import Client from "@/components/Client/Client";
import Contact from "@/components/Contact/Contact";
import Footer from "@/components/Footer/Footer";
import Services from "@/components/Services/Services";
import Showreel from "@/components/Showreel/Showreel";
import Work from "@/components/Work/Work";
import Hero from "@/components/Hero/Hero";
import Head from "next/head";
import KoreanArchive from "@/components/Archive/KoreanArchive";

export default function Home() {
  return (
    <>
      <Head>
        <title>Philippe Layani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Showreel />
      <Work />
      <KoreanArchive />
      <Client />
      <Services />
      <About />
      <Contact />
      <Footer />
    </>
  );
}
