import About from "@/components/About/About";
import Client from "@/components/Client/Client";
import Contact from "@/components/Contact/Contact";
import Footer from "@/components/Footer/Footer";
import Services from "@/components/Services/Services";
import Showreel from "@/components/Showreel/Showreel";
import Work from "@/components/Work/Work";
import Hero from "@/components/Hero/Hero";
import Head from "next/head";
import KoreanArchive from "@/components/Archive/KoreanArchive";
import Archive from "@/components/Archive/Archive";
import useChannelIO from "@/hooks/useChannel";
import KoreanServices from "@/components/Services/KoreanServices";

export default function Home() {
  useChannelIO("191ac84c-8517-4966-89ce-90152c22369e");
  


  return (
    <>
      <Head>
        <title>Wise Rootree</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Hero />
      <Showreel />
      <Work />
      <KoreanArchive />
      <Archive />
      <Client />
      <KoreanServices />
      <Contact />
      <Footer />
    </>
  );
}
