import Description from "@/components/WorkSubPage/Description";
import Hero from "@/components/WorkSubPage/Hero";
import Slider from "@/components/WorkSubPage/Slider";
import Head from "next/head";

const WorkPage = () => {
  return (
    <>
      <Head>
        <title>Wise Rootree - Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Description />
      <Slider />
    </>
  );
};

export default WorkPage;
